import { corsHeaders } from '../lib/cors.js';
import { validateToken } from '../lib/auth.js';

/**
 * Read/write helpers (shared pattern with other handlers).
 */
async function readStore(env) {
  const obj = await env.DATA_BUCKET.get('videos.json');
  if (!obj) return { videos: [], channels: {} };
  try { return await obj.json(); } catch { return { videos: [], channels: {} }; }
}

async function writeStore(env, store) {
  await env.DATA_BUCKET.put('videos.json', JSON.stringify(store, null, 2), {
    httpMetadata: { contentType: 'application/json' },
  });
}

/**
 * Extract video ID from a YouTube URL.
 */
function extractVideoId(url) {
  const m = url.match(/[?&]v=([a-zA-Z0-9_-]{11})/) || url.match(/youtu\.be\/([a-zA-Z0-9_-]{11})/);
  return m ? m[1] : null;
}

/**
 * Get Apify keys from env (comma-separated APIFY_KEYS secret).
 */
function getApifyKeys(env) {
  if (env.APIFY_KEYS) {
    return env.APIFY_KEYS.split(',').map(k => k.trim()).filter(Boolean);
  }
  return [];
}

/**
 * Decode HTML entities in transcript segments.
 */
function decodeEntities(text) {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&apos;/g, "'");
}

/**
 * POST /api/fetch-video
 *
 * Body: { url: "https://youtube.com/watch?v=..." }
 *
 * Fetches metadata via oEmbed, transcript via Apify, ingests into store.
 * Returns the video object with transcript.
 */
export async function handleFetchVideo(request, env) {
  const origin = request.headers.get('Origin') || '';
  const headers = { 'Content-Type': 'application/json', ...corsHeaders(origin) };

  let body;
  try { body = await request.json(); } catch {
    return new Response(JSON.stringify({ error: 'Invalid JSON body' }), { status: 400, headers });
  }

  const { url } = body;
  if (!url || typeof url !== 'string') {
    return new Response(JSON.stringify({ error: 'url is required' }), { status: 400, headers });
  }

  const videoId = extractVideoId(url);
  if (!videoId) {
    return new Response(JSON.stringify({ error: 'Invalid YouTube URL' }), { status: 400, headers });
  }

  // Check if video already exists with transcript
  const store = await readStore(env);
  const existing = (store.videos || []).find(v => v.id === videoId);
  if (existing && existing.hasTranscript) {
    return new Response(JSON.stringify({
      video: existing,
      status: 'already_exists',
      message: 'Video already in library with transcript',
    }), { headers });
  }

  // Step 1: Fetch metadata via YouTube oEmbed (free, no key needed)
  let title = '', thumbnailUrl = '';
  try {
    const oembedResp = await fetch(
      `https://www.youtube.com/oembed?url=https://youtube.com/watch?v=${videoId}&format=json`
    );
    if (oembedResp.ok) {
      const oembed = await oembedResp.json();
      title = oembed.title || '';
      thumbnailUrl = oembed.thumbnail_url || '';
    }
  } catch { /* metadata is nice-to-have */ }

  // Step 2: Fetch transcript via Apify (with key rotation)
  const apifyKeys = getApifyKeys(env);
  if (apifyKeys.length === 0) {
    return new Response(JSON.stringify({ error: 'No Apify keys configured' }), { status: 500, headers });
  }

  let transcript = '';
  let apifyError = null;
  const canonicalUrl = `https://www.youtube.com/watch?v=${videoId}`;

  for (const key of apifyKeys) {
    try {
      const runResp = await fetch(
        `https://api.apify.com/v2/acts/karamelo~youtube-transcripts/runs?waitForFinish=120&token=${key}`,
        {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ urls: [canonicalUrl], preferAutoGeneratedTranscript: true }),
        }
      );

      if (!runResp.ok) {
        const errText = await runResp.text();
        if (runResp.status === 402 || errText.includes('usage') || errText.includes('limit')) {
          apifyError = 'credits exhausted';
          continue;
        }
        apifyError = `Apify error ${runResp.status}`;
        continue;
      }

      const runData = await runResp.json();
      const dsId = runData?.data?.defaultDatasetId;
      if (!dsId) {
        apifyError = 'No dataset returned';
        continue;
      }

      // Fetch dataset items
      const dsResp = await fetch(
        `https://api.apify.com/v2/datasets/${dsId}/items?token=${key}`
      );
      if (!dsResp.ok) {
        apifyError = 'Failed to fetch dataset';
        continue;
      }

      const items = await dsResp.json();
      if (!Array.isArray(items) || items.length === 0) {
        apifyError = 'No transcript items returned';
        break; // Not a key issue — video genuinely has no transcript
      }

      const item = items[0];

      // Handle multiple field formats (the actor has changed formats before)
      if (item.captions && Array.isArray(item.captions)) {
        transcript = item.captions.map(c => decodeEntities(String(c))).join(' ');
      } else if (item.transcript) {
        transcript = String(item.transcript);
      } else if (item.captions_concatenated) {
        transcript = String(item.captions_concatenated);
      } else if (item.text) {
        transcript = String(item.text);
      } else if (item.content) {
        transcript = String(item.content);
      }

      break; // Success (even if transcript is empty — video may not have one)
    } catch (err) {
      apifyError = err.message;
      continue;
    }
  }

  // Step 3: Build video object and ingest
  const now = new Date().toISOString();
  const video = {
    id: videoId,
    title: title || `YouTube Video ${videoId}`,
    url: canonicalUrl,
    thumbnailUrl: thumbnailUrl || `https://i.ytimg.com/vi/${videoId}/hqdefault.jpg`,
    channelId: '',
    date: now,
    durationSeconds: 0,
    viewCount: 0,
    likes: 0,
    commentsCount: 0,
    description: '',
    searchQuery: 'manual',
    topic: 'manual',
    hasTranscript: transcript.length > 0,
    transcriptWordCount: transcript ? transcript.split(/\s+/).filter(Boolean).length : 0,
    transcript,
    summary: null,
    summaryModel: null,
    ingestedAt: now,
  };

  // Merge into store (update if exists, add if new)
  const existingIdx = (store.videos || []).findIndex(v => v.id === videoId);
  if (existingIdx >= 0) {
    // Update existing entry with transcript
    store.videos[existingIdx] = { ...store.videos[existingIdx], ...video, date: store.videos[existingIdx].date };
  } else {
    store.videos.push(video);
  }

  await writeStore(env, store);

  return new Response(JSON.stringify({
    video,
    status: transcript ? 'success' : 'no_transcript',
    message: transcript
      ? `Fetched video with ${video.transcriptWordCount} word transcript`
      : `Video added but no transcript available${apifyError ? ' (' + apifyError + ')' : ''}`,
  }), { headers });
}
